### ISSUE TITLE
Mobile APIs Discussion

### ISSUE THREAD

**Issue by chenop** [meeba-org/meeba-web#17]
Hi @yasmini & @ilansr 

Just sat with @laviavigdor and thought together what are the APIs the mobile needs:

1. Manager Login (First Priority) - request contain username & password, respond contain token? - @yasmini please define
2. Employee status (in shift / not in shift)
3. Clock in
4. Clock out

What do you think? I would like to open an issue for each one once you'll confirm.

**Comment by ilansr** [comment]
From my standpoint and following Yasmin and my discussion a couple of days
ago:

   1. OK
   2. in shift / not in shift is a "subjective" deduction. Should the api
   return this? or should it just return the log of his operations ("clockin"
   /' "clockout" ) activity.
   The latter option is objective and just returns dry data. Is it the
   API's role to give a interpretation of the set of actions that the user has
   done?

   Yasmin and I thought that we should just provide a GET call that returns
   the users latest activity (log of user's opererations)
   eg -
   GET api.meeba.com/api/v1/UserOperations/{user-ID}?fromDate=
   "29/5/2017:00:00Z"&endDate="30/5/2017:00:00Z"

   Response:
   [{ activity-type: "clock-in", time-stamp: "29/5/2017:08:00Z"}, {
   activity-type: "clock-out", time-stamp: "29/5/2017:17:00Z"}]

   Unless we want an additional API that does this kind of interpretation.
   If so, it should be spec'd out
   3. See 2
   4. See 2

**Comment by chenop** [comment]
2. Is fine by me.
3 & 4 are post API calls - what do you mean when you are saying they are like 2?

**Comment by ilansr** [comment]
Right
3+4:
POST  api.meeba.com/api/v1/UserOperations
<http://api.meeba.com/api/v1/UserOperations/%7Buser-ID%7D?fromDate=>
(Access token in header)
{ activity-type: "clock-in", time-stamp: "29/5/2017:08:00Z"}

**Comment by chenop** [comment]
Makes total sense - Thanks.
Regarding the login (1).

Can you please define it?

**Comment by ilansr** [comment]
I will as soon as Yasmin and I agree on an authentication method
