### ISSUE TITLE
[FE - General] design app components structure based on spec/wireframes from product

### ISSUE THREAD

**Issue by ofiron01** [meeba-org/meeba-web#3]

**Comment by ofiron01** [comment]
![screenshot-cacoo com 2017-06-13 16-44-34](https://user-images.githubusercontent.com/4222159/27139136-dd0fefa0-512a-11e7-9071-99678e4ce8b2.png)

**Comment by chenop** [comment]
@ofiron01 Impressive work.

One small comments - The employees view should be added.
